{"name": "Тест входа в систему с невалидными данными", "status": "passed", "description": "Проверка ошибки входа в систему с использованием невалидных данных. Ожидается получение статуса 401 и сообщения об ошибке.", "start": 1700764882340, "stop": 1700764882676, "uuid": "3e7b12a5-1ede-4a75-9b16-34821aa728a1", "historyId": "5800fa9af966348a7b1b46f1429f92aa", "testCaseId": "5800fa9af966348a7b1b46f1429f92aa", "fullName": "tests.test_user_login.TestUserLogin#test_login_with_invalid_data_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "LAPTOP-U8DEQNJF"}, {"name": "thread", "value": "22668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}